name: Sync issues to Freelo

on:
  workflow_dispatch:
  issues:
    types: [opened, edited, closed, reopened, assigned, unassigned]
  issue_comment:
    types: [created, edited, deleted]
permissions:
  issues: write
jobs:
  run-my-action:
    name: Run sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          email: ${{ secrets.FREELO_EMAIL }}
          api-key: ${{ secrets.FREELO_TOKEN }}
          project-id: ${{ vars.FREELO_PROJECT }}
          tasklist-id: ${{ vars.FREELO_TASKLIST }}
          github-token: ${{ secrets.GITHUB_TOKEN }}